kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: testcrds.hindol.com
spec:
  group: hindol.com
  names:
    plural: testcrds
    singular: testcrd
    kind: TestCrd
    shortNames:
      - tcrd
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: This is a placeholder for Name in Test Crd
                description:
                  type: string
                  description: This is a placeholder for Description in Test Crd
                author:
                  type: string
                  description: This is a placeholder for Author in Test Crd