apiVersion: v1
kind: Pod
metadata:
  name: init-test
spec:
  initContainers:
  - name: init-container
    image: busybox:latest
    command: ['sh', '-c', 'echo "Init - Waiting"; sleep 10']
  containers:
  - name: main-container
    image: busybox:latest
    command: ['sh', '-c', 'echo "Main - Running"; sleep 3600']